#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v20
# autospec commit: f35655a
#
Name     : perl-DBIx-Connector
Version  : 0.60
Release  : 31
URL      : https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/DBIx-Connector-0.60.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/DBIx-Connector-0.60.tar.gz
Summary  : 'Fast, safe DBI connection and transaction management'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-DBIx-Connector-license = %{version}-%{release}
Requires: perl-DBIx-Connector-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(DBI)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
DBIx::Connector
DBIx::Connector provides a simple interface for fast and safe DBI
connection and transaction management. Connecting to a database can be
expensive; you don't want your application to re-connect every time you
need to run a query. The efficient thing to do is to hang on to a
database handle to maintain a connection to the database in order to
minimize that overhead. DBIx::Connector lets you do that without having
to worry about dropped or corrupted connections.

%package dev
Summary: dev components for the perl-DBIx-Connector package.
Group: Development
Provides: perl-DBIx-Connector-devel = %{version}-%{release}
Requires: perl-DBIx-Connector = %{version}-%{release}

%description dev
dev components for the perl-DBIx-Connector package.


%package license
Summary: license components for the perl-DBIx-Connector package.
Group: Default

%description license
license components for the perl-DBIx-Connector package.


%package perl
Summary: perl components for the perl-DBIx-Connector package.
Group: Default
Requires: perl-DBIx-Connector = %{version}-%{release}

%description perl
perl components for the perl-DBIx-Connector package.


%prep
%setup -q -n DBIx-Connector-0.60
cd %{_builddir}/DBIx-Connector-0.60
pushd ..
cp -a DBIx-Connector-0.60 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-DBIx-Connector
cp %{_builddir}/DBIx-Connector-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-DBIx-Connector/18b53c405b41e5eeafeebeea6349cc2479726ed9 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DBIx::Connector.3
/usr/share/man/man3/DBIx::Connector::Driver.3
/usr/share/man/man3/DBIx::Connector::Driver::Firebird.3
/usr/share/man/man3/DBIx::Connector::Driver::MSSQL.3
/usr/share/man/man3/DBIx::Connector::Driver::MariaDB.3
/usr/share/man/man3/DBIx::Connector::Driver::Oracle.3
/usr/share/man/man3/DBIx::Connector::Driver::Pg.3
/usr/share/man/man3/DBIx::Connector::Driver::SQLite.3
/usr/share/man/man3/DBIx::Connector::Driver::mysql.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-DBIx-Connector/18b53c405b41e5eeafeebeea6349cc2479726ed9

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
