#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DBIx-Connector
Version  : 0.56
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/D/DW/DWHEELER/DBIx-Connector-0.56.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DW/DWHEELER/DBIx-Connector-0.56.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libd/libdbix-connector-perl/libdbix-connector-perl_0.56-1.debian.tar.xz
Summary  : 'Fast, safe DBI connection and transaction management'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-DBIx-Connector-man
Requires: perl(DBI)
Requires: perl(Module::Build)
Requires: perl(Test::MockModule)
BuildRequires : perl(DBI)
BuildRequires : perl(Module::Build)
BuildRequires : perl(Test::MockModule)

%description
DBIx/Connection version 0.56
============================
DBIx::Connector provides a simple interface for fast and safe DBI connection
and transaction management. Connecting to a database can be expensive; you
don't want your application to re-connect every time you need to run a query.
The efficient thing to do is to hang on to a database handle to maintain a
connection to the database in order to minimize that overhead. DBIx::Connector
lets you do that without having to worry about dropped or corrupted
connections.

%package man
Summary: man components for the perl-DBIx-Connector package.
Group: Default

%description man
man components for the perl-DBIx-Connector package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n DBIx-Connector-0.56
mkdir -p %{_topdir}/BUILD/DBIx-Connector-0.56/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/DBIx-Connector-0.56/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver/Firebird.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver/MSSQL.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver/Oracle.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver/Pg.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver/SQLite.pm
/usr/lib/perl5/site_perl/5.26.1/DBIx/Connector/Driver/mysql.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/DBIx::Connector.3
/usr/share/man/man3/DBIx::Connector::Driver.3
/usr/share/man/man3/DBIx::Connector::Driver::Firebird.3
/usr/share/man/man3/DBIx::Connector::Driver::MSSQL.3
/usr/share/man/man3/DBIx::Connector::Driver::Oracle.3
/usr/share/man/man3/DBIx::Connector::Driver::Pg.3
/usr/share/man/man3/DBIx::Connector::Driver::SQLite.3
/usr/share/man/man3/DBIx::Connector::Driver::mysql.3
